<a href="https://colab.research.google.com/github/Ayyappa9105/ML_workshop/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 1. Perform arithmetic operations on NumPy arrays.

In [ ]:
import numpy as np

In [ ]:
a=np.array([[1,2,3],[1,2,3]])
a.shape

(2, 3)

In [ ]:
b=np.array([[4,5,6],[4,5,6]])
b.shape

(2, 3)

In [ ]:
print("a is \n",a)
print("b is \n",b)
print("sum of two arrays is \n ",(a+b))

a is 
 [[1 2 3]
 [1 2 3]]
b is 
 [[4 5 6]
 [4 5 6]]
sum of two arrays is 
  [[5 7 9]
 [5 7 9]]


2. Write a script to compute the mean and standard deviation of a NumPy array.

Mean :- The average of the values.In numpy there is a method mean.
we  can use it as np.mean(array_name)
Standard deviation Mean :- it is the extended data mean of the values.In numpy there is a method mean.
we  can use it as np.std(array_name)

In [ ]:
import numpy as np

In [ ]:
c=np.array([1,2,3,4,5,6,7,8,9,1,2,3])
print(np.mean(c))
print(np.std(c))

4.25
2.6180463454008347


3. Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [ ]:
import numpy as np

In [ ]:
d=np.arange(10,50,5)
print(d)

[10 15 20 25 30 35 40 45]


4. Reshape the array into a 2x4 matrix.

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4,5,6,7,8])
b=a.reshape(2,4)
print("array is",a)
print("2X4 matrices is \n",b)

array is [1 2 3 4 5 6 7 8]
2X4 matrices is 
 [[1 2 3 4]
 [5 6 7 8]]


5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.
• Replace all elements greater than 4 with 0.

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
a=arr[1:,1:]
print("the matrices which contains last two rows and two colums \n",a)
arr[arr>4]=0
print("replace all elements which are greate than 4 with 0 \n",arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
the matrices which contains last two rows and two colums 
 [[5 6]
 [8 9]]
replace all elements which are greate than 4 with 0 [[1 2 3]
 [4 0 0]
 [0 0 0]]


6.  Create two 1D arrays:
• a = np.array([1, 2, 3])
• b = np.array([4, 5, 6])
• Perform element-wise addition, multiplication, and division.

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("array a is",a)
print("array b is",b)
print("addition:",a+b)
print("multiplication:",a*b)
print("Division:",a/b)

array a is [1 2 3]
array b is [4 5 6]
addition: [5 7 9]
multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


 7. Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.
• Maximum value of the entire array.
• Sum of all elements.

In [ ]:
import numpy as np

In [ ]:
arr=np.array([[[[1,2,3,4],[1,2,3,4],[1,2,5,4],[1,2,3,4]]]])
max_val=np.max(arr)
print(max_val)
c1=arr[:,:,:,0]
print(np.mean(c1))
c2=arr[:,:,:,1]
print(np.mean(c2))
c3=arr[:,:,:,2]
print(np.mean(c3))
c4=arr[:,:,:,3]
print(np.mean(c4))
print(np.sum(arr))




5
1.0
2.0
3.5
4.0
42


8.  Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
r=(arr+10)*2
print(r)



[22 24 26 28]


9. Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
• Extract the first two rows and the last three columns from each "layer."
• Replace all elements divisible by 3 with -1.

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1, 101, size=(3, 4, 5))
print("3D array is \n",arr)
a1=arr[1]
print("second layer \n",a1)
a2=arr[:,:2,0:3]
print("first two rows and last three colums from each layer \n",a2)
arr[arr%3==0]=-1
print("Repalced by -1 \n",arr)

3D array is 
 [[[25 51 33 25 44]
  [29 78  6 29 80]
  [59 18 77 35  9]
  [97 98 88 74 48]]

 [[98 34 10 31 41]
  [ 6  9 91 28 57]
  [54 40 66 76 50]
  [53 98 98 42  2]]

 [[28 37 80 42 17]
  [88 72  5 16 76]
  [24 39 76 90 46]
  [75 23 60 70 57]]]
second layer 
 [[98 34 10 31 41]
 [ 6  9 91 28 57]
 [54 40 66 76 50]
 [53 98 98 42  2]]
first two rows and last three colums from each layer 
 [[[25 51 33]
  [29 78  6]]

 [[98 34 10]
  [ 6  9 91]]

 [[28 37 80]
  [88 72  5]]]
Repalced by -1 
 [[[25 -1 -1 25 44]
  [29 -1 -1 29 80]
  [59 -1 77 35 -1]
  [97 98 88 74 -1]]

 [[98 34 10 31 41]
  [-1 -1 91 28 -1]
  [-1 40 -1 76 50]
  [53 98 98 -1  2]]

 [[28 37 80 -1 17]
  [88 -1  5 16 76]
  [-1 -1 76 -1 46]
  [-1 23 -1 70 -1]]]


 Work with broadcasting and advanced operations in NumPy.
Create a NumPy array arr of shape (3, 3) with random integers between  
1 and 20. Perform the following:
• Subtract the mean of each row from its respective elements (row-wise
normalization).
• Create a new array by squaring all the elements in arr.
• Find the indices of the top 3 maximum values in the entire array.

In [2]:
import  numpy as np

In [3]:
arr = np.random.randint(1, 21, size=(3, 3))
print("array is\n",arr)
r1=arr[0:1]-np.mean(arr[0:1])
r2=arr[1:2]-np.mean(arr[1:2])
r3=arr[2:3]-np.mean(arr[2:3])
print("\n",r1,"\n",r2,"\n",r3)
print("square elements array is \n",arr**2)
b=np.array([10,7,18,93,63,8,45])
print(b)
top_3_indices = np.unravel_index(np.argsort(arr.ravel())[-3:], arr.shape)
print("\nIndices of Top 3 Maximum Values:",top_3_indices)







array is
 [[ 1 11  8]
 [ 8 20  4]
 [20  3  5]]

 [[-5.66666667  4.33333333  1.33333333]] 
 [[-2.66666667  9.33333333 -6.66666667]] 
 [[10.66666667 -6.33333333 -4.33333333]]
square elements array is 
 [[  1 121  64]
 [ 64 400  16]
 [400   9  25]]
[10  7 18 93 63  8 45]

Indices of Top 3 Maximum Values: (array([0, 1, 2]), array([1, 1, 0]))
